### ISSUE TITLE
Recherche DM existant

### ISSUE THREAD

**Issue by stefym** [mariemonchoix/Genie-Logiciel#5]

**Comment by AnaisKormann** [comment]
- Recherches sur le fonctionnement de base d'un pacemaker
- Quels sont les constituants d'un pacemaker
- Les entreprises leaders sur le marché du pacemaker
- Caractéristiques des pacemakers actuels (durée de vie etc.)
- Mise en place du dispositif (opération etc.)
- Le fonctionnement de la télésurveillance (comment certains pacemaker transmettent leurs informations)

Pour plus détails, voir dans Genie-Logiciel/Collection Informations/Existant
